### ISSUE TITLE
可能会造成 evil 粘贴行为异常

### ISSUE THREAD

**Issue by smartepsh** [twlz0ne/whitespace4r.el#2]
### 问题描述

在 evil 中使用 `yy` 和 `p` 命令，正常情况下，无论光标在哪个位置，应该会粘贴为新的一行；
但引入本包后，粘贴的行为会变为从光标处开始粘贴，而非新行。

### 期望

不影响 evil 的行为。

**Comment by twlz0ne** [comment]
你可否提供一个可重现问题的用最小配置和具体步骤？

我用以下步骤无法重现：

1. 获取/更新源代码

```sh
$ git clone https://github.com/twlz0ne/whitespace4r.el whitespace4r && cd whitespace4r
# or $ cd whitespace4r && git pull
```

2. 启动最小配置 ([🔗emacsq.sh](https://github.com/twlz0ne/emacsq-sh))

```sh
$ emacsq.sh -L . -P evil,whitespace4r -M evil-mode,whitespace4r-mode --eval "(switch-to-buffer \"*scratch*\")" -nw
```

3. 复制粘贴操作
3.1 `gg` 行首
3.2 `yy` 复制
3.3 `p`  粘贴

4. 检查 `*scratch*` 缓冲内容

``` text
;; This buffer is for text that is not saved, and for Lisp evaluation.
;; This buffer is for text that is not saved, and for Lisp evaluation.
;; To create a file, visit it with C-x C-f and enter text in its buffer.
```

环境&版本：

- macOS 10.13.6
- Emacs 29.0.50
- Packages: evil-20211128.2232, whitespace4r-0.1.9

**Comment by smartepsh** [comment]
好的，我去尝试下，可能会晚些（周末）给到您。

**Comment by smartepsh** [comment]
咱俩的环境可能不太一样……我使用你这个内容也是一样的问题。

### 启动命令

```bash
./emacsq.sh -L . -P evil,whitespace4r -M evil-mode,whitespace4r-mode
```

### `gg -> yy -> p` 的结果如下：
<img width="546" alt="image" src="https://user-images.githubusercontent.com/3273295/156370204-f249cf99-6595-4688-b806-8ebd09411fb5.png">

### 环境&版本

macOS 12.2.1
Emacs 28.0.91
Packages: evil-20220217.748, whitespace4r-20220116.2051

**Comment by twlz0ne** [comment]
> whitespace4r-20220116.2051

请更新代码：

<pre>
⋊> [~/.r/emacs-whitespace4r] git hist
* 161cc17  (HEAD -> master, origin/master) 🐞 Fix wrong highlight in c-mode 2022-03-01
* 3ca8c10  🐞 Fix undo issue after pretty print 2022-02-25
* a36dc24  🐞 Fix undo issue after indent region 2022-01-30
* 5f4a8d9  📝 Update README 2022-01-28
* af1c0e9  🐞 Fix "Selecting deleted buffer" error 2022-01-24
* 1c0a0dd  Visualize trailing blanks 2022-01-21
* e07b548  Add faces&variables instead of taking directly from whitespace-mode 2022-01-18
* 1c1935a  Fix CI 2022-01-18
* ef0366e  Remove advices to fix undo issue 2022-01-17
* b5c6de2  whitespace4r-display-mappings: New variable 2022-01-17
<b>* 1778dc5  Fix CI badge 2022-01-16 «---- 你正在用的版本</b>
* 3a02eae  Fix advices 2022-01-16
* 25d3fc2  Init commit 2022-01-12
</pre>

**Comment by smartepsh** [comment]
我使用的 use-package ，导致没有升级这个包。。。

谢谢回复，新版本确实没问题了。
